# Generated by Django 3.1.1 on 2020-09-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='material_shape')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_x', models.FloatField(verbose_name='size_x')),
                ('size_y', models.FloatField(blank=True, default=None, null=True, verbose_name='size_y')),
                ('size_z', models.FloatField(blank=True, default=None, null=True, verbose_name='size_z')),
                ('sizes', models.CharField(blank=True, default=None, max_length=100, verbose_name='additional sizes')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='material_name')),
                ('abbreviation', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Abbreviation')),
            ],
        ),
    ]
