# Generated by Django 3.1.1 on 2020-09-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.manufacturer')),
                ('material_shape', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.materialshape')),
                ('material_size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.materialsize')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.materialtype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('material_type', 'material_shape', 'material_size'), name='material'),
        ),
    ]
