# Generated by Django 3.1.1 on 2020-09-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200917_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
            ],
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'MATERIAL', 'verbose_name_plural': 'MATERIALS'},
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.materialcolor'),
        ),
    ]
