# Generated by Django 3.1.1 on 2020-09-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200917_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialThickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.FloatField(default=0.125, verbose_name='Thickness')),
                ('measuring_system', models.CharField(max_length=8, verbose_name='Measuring system')),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.manufacturer'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_shape',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.materialshape'),
        ),
    ]
