# Generated by Django 3.1.1 on 2020-09-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200917_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialthickness',
            options={'verbose_name': 'Thickness', 'verbose_name_plural': 'Thickness'},
        ),
        migrations.AddField(
            model_name='material',
            name='material_thickness',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.materialthickness'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_shape',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.materialshape'),
        ),
        migrations.AlterField(
            model_name='materialthickness',
            name='measuring_system',
            field=models.CharField(choices=[('in', 'Imperial'), ('mm', 'CI')], default='in', max_length=8, verbose_name='Measuring system'),
        ),
    ]
