# Generated by Django 3.1.1 on 2020-09-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200917_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['manufacturer']},
        ),
        migrations.AlterModelOptions(
            name='materialsize',
            options={'ordering': ['size_x', 'size_y', 'size_z']},
        ),
        migrations.AlterModelOptions(
            name='materialthickness',
            options={'ordering': ['thickness'], 'verbose_name': 'Thickness', 'verbose_name_plural': 'Thickness'},
        ),
        migrations.AlterModelOptions(
            name='materialtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.materialcolor'),
        ),
        migrations.AlterField(
            model_name='material',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.manufacturer'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_shape',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.materialshape'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.materialsize'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_thickness',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.materialthickness'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.materialtype'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='PO')),
                ('material', models.ManyToManyField(related_name='pos', through='inventory.MaterialAmount', to='inventory.Material')),
            ],
            options={
                'verbose_name': 'Purchase order',
                'verbose_name_plural': 'Purchase orders',
            },
        ),
        migrations.AddField(
            model_name='materialamount',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_amounts', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='materialamount',
            name='po',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_amounts', to='inventory.purchaseorder'),
        ),
    ]
