# Generated by Django 3.1.1 on 2020-09-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200919_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialamount',
            options={'verbose_name': 'Material amount', 'verbose_name_plural': 'Materials amount'},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='date_ordered',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='date_received',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='materialamount',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_amounts', to='inventory.material'),
        ),
    ]
