# Generated by Django 3.1.1 on 2020-09-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200919_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'PO#', 'verbose_name_plural': 'PO##'},
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='material',
        ),
    ]
