# Generated by Django 3.0.7 on 2020-09-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200923_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pallet', to='inventory.Material'),
        ),
    ]
