# Generated by Django 3.0.7 on 2020-07-16 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200601_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(choices=[('PM', 'Project manager'), ('Pr', 'Production'), ('MP', 'Machine operator'), ('TW', 'Table worker'), ('Ud', 'Undefined')], max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'verbose_name': 'Panel', 'verbose_name_plural': 'Panels'},
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_quantity',
            field=models.IntegerField(blank=True, default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_title',
            field=models.CharField(max_length=10, verbose_name='Panel name'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_folder',
            field=models.CharField(blank=True, default='D:\\Users\\Public\\Downloads\\01ProjectEmptyFiles', max_length=200, verbose_name='Folder'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_title',
            field=models.CharField(max_length=10, verbose_name='Release name'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loose_items', models.BooleanField(default=False)),
                ('outsource_paint', models.BooleanField(default=False)),
                ('zee_hats_angels', models.IntegerField(blank=True, null=True)),
                ('flashing', models.IntegerField(blank=True, null=True)),
                ('coping', models.IntegerField(blank=True, null=True)),
                ('splice_plate', models.IntegerField(blank=True, null=True)),
                ('blade_screen', models.IntegerField(blank=True, null=True)),
                ('perf', models.IntegerField(blank=True, null=True)),
                ('plate_panels', models.IntegerField(blank=True, null=True)),
                ('frames', models.IntegerField(blank=True, null=True)),
                ('strapping', models.IntegerField(blank=True, null=True)),
                ('clips', models.IntegerField(blank=True, null=True)),
                ('misc', models.IntegerField(blank=True, null=True)),
                ('est_mh', models.IntegerField(blank=True, null=True)),
                ('rel_date', models.DateField(auto_now_add=True)),
                ('requested_ship_date', models.DateField(blank=True)),
                ('shipped_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('In progress', 'In progress'), ('Delayed', 'Delayed'), ('Producing', 'Producing'), ('Ready for Pick Up', 'Ready for Pick Up'), ('Partial Pick Up', 'Partial Pick Up'), ('Shipped', 'Shipped')], default='In progress', max_length=20)),
                ('shipped_to_location', models.CharField(blank=True, max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('project_manager', models.ForeignKey(limit_choices_to={'title': 'PM'}, on_delete=django.db.models.deletion.CASCADE, to='app.Staff')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Release')),
            ],
        ),
    ]
