# Generated by Django 3.0.6 on 2020-06-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200, verbose_name='Project name')),
                ('project_number', models.IntegerField(max_length=5, verbose_name='Project number')),
                ('project_path', models.CharField(max_length=200, verbose_name='Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_title', models.CharField(max_length=10, verbose_name='Project name')),
                ('release_folder', models.CharField(max_length=200, verbose_name='Folder')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_title', models.CharField(max_length=10, verbose_name='Project name')),
                ('panel_quantity', models.IntegerField(max_length=7, verbose_name='Quantity')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Release')),
            ],
        ),
    ]
