# Generated by Django 3.0.6 on 2020-06-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='panel_quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.IntegerField(verbose_name='Project number'),
        ),
    ]
