# Generated by Django 3.0.6 on 2020-06-01 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_auto_20200601_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='panel',
            new_name='release',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='release',
            new_name='project',
        ),
    ]
