# Generated by Django 3.1.1 on 2020-10-12 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200925_1314'),
        ('app', '0002_auto_20200923_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='purchase_order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='task',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.release'),
        ),
    ]
