# Generated by Django 3.1.1 on 2020-10-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201012_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='project',
            name='mail_address',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Mail address'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_path',
            field=models.CharField(blank=True, max_length=200, verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Project name'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('project_number',), name='project_number'),
        ),
    ]
