# Generated by Django 3.1.1 on 2020-10-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200925_1314'),
        ('app', '0004_auto_20201012_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.PositiveIntegerField(verbose_name='Project number'),
        ),
        migrations.AlterField(
            model_name='project',
            name='purchase_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorder'),
        ),
        migrations.CreateModel(
            name='ReleaseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.release')),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='release_material',
            field=models.ManyToManyField(through='app.ReleaseMaterial', to='inventory.Material'),
        ),
    ]
