# Generated by Django 3.0.8 on 2020-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_auto_20200716_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='panel_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Quantity'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('release_title', 'project'), name='unique pro releases'),
        ),
    ]
