# Generated by Django 3.1.1 on 2020-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201012_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasematerial',
            options={'verbose_name': 'Release material'},
        ),
        migrations.AlterField(
            model_name='task',
            name='requested_ship_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='shipped_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('release',), name='task_uniques'),
        ),
    ]
