# Generated by Django 3.1.1 on 2020-10-15 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_auto_20200925_1314'),
        ('app', '0006_auto_20201013_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'layout',
                'verbose_name_plural': 'layouts',
            },
        ),
        migrations.CreateModel(
            name='LayoutPanels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Nest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True, verbose_name='name')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='panel',
            name='unique panel_info',
        ),
        migrations.RemoveConstraint(
            model_name='release',
            name='unique pro release_view',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='modified',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='release',
            name='release_material',
        ),
        migrations.AddField(
            model_name='panel',
            name='bend_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='bending_operator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bending_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panel',
            name='fabricated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='fabricator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabricator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panel',
            name='punch_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='punching_operator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punching_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panel',
            name='punching_operator_helper',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_operator_helper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panel',
            name='size_x',
            field=models.FloatField(default=56.0, verbose_name='X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panel',
            name='size_y',
            field=models.FloatField(default=30.0, verbose_name='Y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='grain_direction',
            field=models.BooleanField(default=False, verbose_name='GD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.materialcolor'),
        ),
        migrations.AddField(
            model_name='release',
            name='material_thickness',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.materialthickness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='material_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.materialtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='provided_material',
            field=models.ManyToManyField(blank=True, through='app.ReleaseMaterial', to='inventory.Material'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_title',
            field=models.CharField(max_length=10, verbose_name='Panel title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(groups=2), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Project title'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_folder',
            field=models.CharField(blank=True, default='PD', max_length=200, verbose_name='Folder'),
        ),
        migrations.AddConstraint(
            model_name='panel',
            constraint=models.UniqueConstraint(fields=('release', 'panel_title'), name='unique panels'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('release_title', 'project'), name='unique pro releases'),
        ),
        migrations.AddField(
            model_name='nest',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.release'),
        ),
        migrations.AddField(
            model_name='layoutpanels',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.layout'),
        ),
        migrations.AddField(
            model_name='layoutpanels',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.panel'),
        ),
        migrations.AddField(
            model_name='layout',
            name='nest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nest'),
        ),
        migrations.AddField(
            model_name='layout',
            name='panels',
            field=models.ManyToManyField(through='app.LayoutPanels', to='app.Panel'),
        ),
        migrations.AddConstraint(
            model_name='layout',
            constraint=models.UniqueConstraint(fields=('name', 'nest'), name='unique layout'),
        ),
    ]
