# Generated by Django 3.1.1 on 2020-11-19 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20201015_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': "Layout's panel",
            },
        ),
        migrations.AlterModelOptions(
            name='nest',
            options={'verbose_name': 'Nest', 'verbose_name_plural': 'Nests'},
        ),
        migrations.AlterModelOptions(
            name='releasematerial',
            options={'verbose_name': 'Expected material usage'},
        ),
        migrations.AddField(
            model_name='layout',
            name='produced',
            field=models.PositiveIntegerField(default=0, verbose_name='Produced'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='bend_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='bending_operator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bending_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panel',
            name='fabricated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='fabricator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabricator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panel',
            name='punch_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='punching_operator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punching_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panel',
            name='punching_operator_helper',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_operator_helper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LayoutPanels',
        ),
        migrations.AddField(
            model_name='layoutpanel',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.layout'),
        ),
        migrations.AddField(
            model_name='layoutpanel',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.panel'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='panels',
            field=models.ManyToManyField(through='app.LayoutPanel', to='app.Panel'),
        ),
    ]
